{% set name = "molearn" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Degiacomi-Lab/molearn/archive/v{{ version }}.tar.gz
  sha256: 4b6ff37271e181250450164756fd0ea1fd0e3dae0e4a03adc1cc81cb613f83f5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - __unix
    - python >=3.6
    - numpy
    - pytorch
    - biobox
    - openmmtorchplugin
test:
  imports:
    - molearn
  source_files:
    - test
  commands:
    - pip check
    - cd test
    - python example_script.py
  requires:
    - pip

about:
  home: https://github.com/Degiacomi-Lab/molearn
  license_file: LICENSE
  license: GPL-3.0-only
  summary: Molearn contains methods to train neural networks on ensembles of molecular conformations
  description: |
    This software trains a generative neural network on an ensemble of molecular conformations (typically
    obtained by molecular dynamics). The trained model can be used to generate new, plausible
    conformations repesentative of poorly sampled transition states.
  doc_url: https://github.com/Degiacomi-Lab/molearn
  dev_url: https://github.com/Degiacomi-Lab/molearn

extra:
  recipe-maintainers:
    - SCMusson
    - degiacom
